server:
    port: 8080
spring:
    application:
        name: restful
    devtools:
        livereload:
            enabled: true
        remote:
            restart:
                enabled: true
    thymeleaf:
        cache: false
        encoding: utf-8
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
    servlet:
        multipart:
            enabled: true
            location: C:\temp
            max-file-size: 2MB
            max-request-size: 10MB
            file-size-threshold: 0B
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    datasource:
        # 使用Druid链接数据池 默认使用Hikari
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        # hikari:
        #     max-lifetime: 1800000 # 30 minutes
        #     idle-timeout: 600000 # 10 minutes
        #     connection-timeout: 30000 # 30 seconds
        #     minimum-idle: 5
        #     maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
mybatis:
    type-aliases-package: com.restful.entity
    mapper-locations: classpath:mappers/*.xml
pagehelper:
    #指明当前查询的是MySQL数据库
    helper-dialect: mysql
    #启用合理化，当pageNum小于1时查询第1页，当pageNum大于页数时查询最后一页
    reasonable: true
    #是否自动分页，依据的是入参，如果参数中有pageNum，pageSize分页参数，则会自动分页
    support-methods-arguments: true
    #如果POJO或者Map中发现了countSql属性，就作为count参数使用
    params: count=countSql
springdoc:
    swagger-ui:
        path: /swagger-ui.html
