server:
    port: 8080
spring:
    application:
        name: restful
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    servlet:
        multipart:
            enabled: true
            location: classpath:/upload/
            max-file-size: 2MB
            max-request-size: 10MB
            file-size-threshold: 0B
