server:
    port: 8080
spring:
    application:
        name: restful
    thymeleaf:
        cache: false
        encoding: utf-8
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
    servlet:
        multipart:
            enabled: true
            location: C:\temp
            max-file-size: 2MB
            max-request-size: 10MB
            file-size-threshold: 0B
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
springdoc:
    swagger-ui:
        path: /swagger-ui.html
