spring:
    application:
        name: demo
    profiles:
        active:
            - dev
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            exclude: static/**
server:
    port: 8081
