# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
logging:
    level:
        jdbc: OFF
        sqltiming: DEBUG
        resultsettable: DEBUG
server:
    port: 8080
user:
    username: shulu2
    password: 123456
    telephone: 13388888888
city:
    - beijing
    - shanghai
    - hangzhou
    - shenzhen